services:
  strapi:
    image: node:20-alpine
    container_name: unispark-strapi
    working_dir: /srv/app
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=development
      - DATABASE_CLIENT=sqlite
      - DATABASE_FILENAME=.tmp/data.db
      - HOST=0.0.0.0
      - PORT=1337
    volumes:
      - ./:/srv/app
      - /srv/app/node_modules
      - /srv/app/.tmp
    restart: unless-stopped
    command: sh -c "npm install && npm run develop"
